version: 2

models:
  - name: vw_fct_copilot_ai_api_activity_detail
    description: "copilot api data"
    columns:
      - name: vh_tenant_id
        description: "The primary key for this table"
        data_tests:
          - not_null

  - name: vw_dim_template_metrics
    description: "refined version of template galaxy dataset"
    columns:
      - name: tenant_id
        description: "The primary key for this table"
        data_tests:
          - not_null
      
          ## fct_addins_desktop_refresh_activity
          ## fct_addins_365_refresh_activity 
          ##
  - name: int_models_pcs_list
    description: >
      Mapping table identifying whether a model belongs to the predefined
      PCS model list based on MT Server model metadata.

    columns:
      - name: vh_tenant_id
        description: Concatenation of datacenter and tenant_id.
        tests:
          - not_null

 ##   tests:
 ##     - dbt_utils.unique_combination_of_columns:
 ##         arguments:
 ##           combination_of_columns:
 ##             - vh_tenant_id
 ##             - id