version: 2

models:
  - name: vw_fct_vcp_api_activity_detail
    description: "copilot api data"
    columns:
      - name: vh_tenant_id
        description: "The primary key for this table"
        data_tests:
          - not_null

  - name: vw_dim_production_customer_usage_info
    description: "master table for product usage at the customer level"
    columns:
      - name: vena_hub_tenant_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


      
          ## fct_addins_desktop_refresh_activity
          ## fct_addins_365_refresh_activity 
          ##
